/* Copyright (C) 2014 CompleteDB LLC.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the Apache License Version 2.0 http://www.apache.org/licenses.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 *
 */

package pubsubsql; 

import com.google.gson.Gson;
import java.nio.charset.Charset;
import java.util.*;

public class Client {

	/**
	* Connect connects the Client to the pubsubsql server.
	* Address string has the form host:port.
	* 
	*/
	public boolean Connect(String address) {
		Disconnect();
		// validate address
		int sep = address.indexOf(':');	
		if (sep < 0) {
			setErrorString("Invalid network address");
			return false;
		}
		// set host and port
		host = address.substring(0, sep);	
		int portIndex = sep + 1;
		if (portIndex >= address.length()) {
			setErrorString("Port is not provided");
			return false;
		}	
		int port = toPort(address.substring(portIndex));
		if (port == 0) {
			setErrorString("Invalid port");
			return false;
		}
		
		//
		try {
			java.net.Socket socket = new java.net.Socket();
			socket.connect(new java.net.InetSocketAddress(host, port), CONNECTION_TIMEOUT);
			rw.Set(socket);
			return rw.Valid();
		} 
		catch (Exception e) {
			setError(e);
		}	
		return false;
	}

	/**
	* Disconnect disconnects the Client from the pubsubsql server.
	* 
	*/
	public void Disconnect() {
		backlog.clear();	
		write("close");
		// write may generate error so we reset after instead
		reset();
		rw.Close();
	}
	
	/**
	* Connected returns true if the Client is currently connected to the pubsubsql server.
	* 
	*/
	public boolean Connected() {
		return rw.Valid();
	}

	
	/**
	* Ok determines if the last command executed against the pubsubsql server succeeded. 
	* 
	*/
	public boolean Ok() {
		return IsNullOrEmpty(err);
	}

			
	/**
	* Failed determines if the last command executed against the pubsubsql server failed. 
	* 
	*/
	public boolean Failed() {
		return !Ok();
	}

	/**
	* Failed determines if the last command executed against the pubsubsql server failed. 
	* 
	*/
	public String Error() {
		return NotNull(err);	
	}

	/** 
	* Error returns an error message when the last command executed against 
	* the pubsubsql server fails.
	* Functions that may generate an error are [Connect, Execute, NextRow, WaitForPubSub]
	*/
	public boolean Execute(String command) {
		reset();
		boolean ok = write(command);
		NetHeader header = new NetHeader();
		while (ok) {
			reset();
			byte[] bytes = readTimeout(0, header);
			if (Failed()) return false;
			if (bytes == null) {
				setErrorString("Timed out");
				return false;
			}
			if (header.RequestId == requestId) {
				// response we are waiting for
				return unmarshallJSON(bytes);
			} else if (header.RequestId == 0) {
				//backlog
				backlog.add(bytes);
			} else if (header.RequestId < requestId) {
				// we did not read full result set from previous command irnore it
				reset();
			} else {
				invalidRequestIdError();
				return false;
			}
		}
		return false;
	}

	/** 
	* JSON returns a response string in JSON format from the 
	* last command executed against the pubsubsql server.
	*/
	public String JSON() {
		return NotNull(rawjson);
	}

		
	/** 
	* Action returns an action string from the response 
	* returned by the last command executed against the pubsubsql server.
	*/
	public String Action() {
		return NotNull(response.action);
	}

	/** 
	* PubSubId returns a unique identifier generated by the pubsubsql server when 
	* a Client subscribes to a table. If the client has subscribed to more than  one table, 
	* PubSubId should be used by the Client to uniquely identify messages 
	* published by the pubsubsql server.
	*/
	public String PubSubId() {
		return NotNull(response.pubsubid);
	}

	/**
	* RowCount returns the number of rows in the result set returned by the pubsubsql server.
	*/
	public int RowCount() {
		return response.rows;
	}

	
	/**
	* NextRow is used to move to the next row in the result set returned by the pubsubsql server.    
	* When called for the first time, NextRow moves to the first row in the result set.
	* Returns false when all rows are read or if there is an error.
	* To find out if false was returned because of an error, use Ok or Failed functions. 
	*/
	public boolean NextRow() {
		while (Ok()) {
			// no result set
			if (response.rows == 0) return false;
			if (response.fromrow == 0 || response.torow == 0) return false;
			// the current record is valid
			record++;
			if (record <= (response.torow - response.fromrow)) return true;
			// we reached the end of the result set?
			if (response.rows == response.torow) {
				record--;
				return false;
			}
			// there is another batch of data
			reset();
			NetHeader header = new NetHeader();
			byte[] bytes = readTimeout(0, header);
			if (Failed()) return false;
			if (bytes == null) {
				setErrorString("Timed out");
				return false;
			}
			if (header.RequestId != requestId) {
				invalidRequestIdError();
				return false;
			}
			unmarshallJSON(bytes);
		}
		return false;
	}

	/**
	* Value returns the value within the current row for the given column name.
	* If the column name does not exist, Value returns an empty string.	
	*/
	public String Value(String column) {
		if (response.data == null) return "";
		if (response.data.size() <= record) return "";
		int ordinal = getColumn(column);
		if (ordinal == -1) return "";
		//
		return response.data.get(record).get(ordinal);
	}
	
	/**
	* ValueByOrdinal returns the value within the current row for the given column ordinal.
	* The column ordinal represents the zero based position of the column in the Columns collection of the result set.
	* If the column ordinal is out of range, ValueByOrdinal returns an empty string.	
	*/
	public String ValueByOrdinal(int ordinal) {
		if (ordinal == -1) return "";
		if (response.data == null) return "";
		if (response.data.size() <= record) return "";
		if (ordinal >= response.columns.size()) return "";
		return response.data.get(record).get(ordinal);
	}

	/**	
	* HasColumn determines if the column name exists in the columns collection of the result set.
	*/
	public boolean HasColumn(String column) {
        return getColumn(column) != -1;
	}

	/**	
	* ColumnCount returns the number of columns in the columns collection of the result set. 
	*/
	public int ColumnCount() {
		if (response.columns == null) return 0;
		return response.columns.size();
	}

	/**
	*Columns returns the column names in the columns collection of the result set. 
	*/
	public Iterable<String> Columns() {
		return response.columns;
	}

	/**
	* WaitForPubSub waits until the pubsubsql server publishes a message for
	* the subscribed Client or until the timeout interval elapses.
	* Returns false when timeout interval elapses or if there is and error.
	* To find out if false was returned because of an error, use Ok or Failed functions. 
	*/
	public boolean WaitForPubSub(int timeout) {
		if (timeout <= 0) return false;		
		reset();
		// process backlog first
		if (backlog.size() > 0) {
			byte[] bytes = backlog.remove();
			return unmarshallJSON(bytes);
		}
		for (;;) {
			NetHeader header = new NetHeader();
			byte[] bytes = readTimeout(timeout, header);
			if (Failed()) return false;
			if (bytes == null) return false; 
			if (header.RequestId == 0) { 
				return unmarshallJSON(bytes);			
			}
			// this is not pubsub message; are we reading abandoned result set?
			// ignore and continue
		}
	}

	// helper functions
	private boolean IsNullOrEmpty(String str) {
		return (str == null || str.length() == 0);
	}

	private String NotNull(String str) {
		if (str == null) return "";
		return str;
	}

	private int toPort(String port) {
		try {
			return Integer.parseInt(port); 	
		} 
		catch (Exception e) {
				
		}
		return 0;
	}

	private void reset() {
		err = "";
		response = new ResponseData();
		rawjson = null;
		record = -1;
	}

	private void hardDisconnect() {
		backlog.clear();
		rw.Close();
		reset();
	}

	private boolean write(String message) {
		try {
			if (!rw.Valid()) throw new Exception("Not connected");
			requestId++;
			rw.WriteWithHeader(requestId, message.getBytes(UTF8_CHARSET));
			return true;

		} 
		catch (Exception e) {
			hardDisconnect();
			setError(e);
		}
		return false;
	}

	private byte[] readTimeout(int timeout, NetHeader header) {
		try {
			if (!rw.Valid()) throw new Exception("Not connected");
			return rw.ReadTimeout(timeout, header);
		}		
		catch (Exception e) {
			hardDisconnect();
			setError(e);
		}
		return null;
	}

	private void setErrorString(String err) {
		reset();
		this.err = err;
	}

	private void setError(Exception e) {
		String err = e.getMessage();
		if (IsNullOrEmpty(err)) err = "Unknown error";
		setErrorString(err);
	}

	private void invalidRequestIdError() {
		setErrorString("Protocol error invalid request id");
	}

	private boolean unmarshallJSON(byte[] bytes) {
		try {
			Gson gson = new Gson();
			rawjson = new String(bytes, UTF8_CHARSET);
			response = gson.fromJson(rawjson, ResponseData.class);
			if (!response.status.equals("ok")) throw new Exception(response.msg); 
			setColumns();
			return true;
		}
		catch (Exception e) {
			setError(e);	
		}
		return false; 
	}

	private void setColumns() {
		if (response.columns != null) {
			int index = 0;
			for(String column : response.columns) {
				columns.put(column, index);
				index++;
			}
		}	
	}

	private int getColumn(String column) {
		Integer ordinal = columns.get(column);
		if (ordinal == null) return -1;
		return (int)ordinal;
	}

	private final Charset UTF8_CHARSET = Charset.forName("UTF-8");
	private int CONNECTION_TIMEOUT = 500;
	private int requestId = 1;
	private String host;
	private int port;
	private String err;
	private NetHelper rw = new NetHelper();
	private ResponseData response = new ResponseData();
	private String rawjson = null;
	private int record = -1;
	private Hashtable<String, Integer> columns = new Hashtable<String, Integer>();
	private LinkedList<byte[]> backlog = new LinkedList<byte[]>();
}

